version: '3.9'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Bp220244
      MYSQL_DATABASE: NumerEquation
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    ports:
      - "3310:3306"

  server:
    build: ./back/
    ports:
      - "8800:8800"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: Bp220244
      DB_NAME: NumerEquation
      DB_PORT: 3306

  app:
    build: ./my-app/
    ports:
      - "3000:3000"
    depends_on:
      - server